/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as EspecialidadesRouteImport } from './routes/especialidades'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AgendamentoRouteImport } from './routes/agendamento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsuariosRouteImport } from './routes/app.usuarios'
import { Route as AppSolicitacoesRouteImport } from './routes/app.solicitacoes'
import { Route as AppProfissionaisRouteImport } from './routes/app.profissionais'
import { Route as AppPacientesRouteImport } from './routes/app.pacientes'
import { Route as AppNotificacoesRouteImport } from './routes/app.notificacoes'
import { Route as AppMinhaAgendaRouteImport } from './routes/app.minha-agenda'
import { Route as AppMeusPacientesRouteImport } from './routes/app.meus-pacientes'
import { Route as AppMeuPerfilRouteImport } from './routes/app.meu-perfil'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as ApiSitemapDotxmlRouteImport } from './routes/api/sitemap[.]xml'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisRoute = ProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecialidadesRoute = EspecialidadesRouteImport.update({
  id: '/especialidades',
  path: '/especialidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentoRoute = AgendamentoRouteImport.update({
  id: '/agendamento',
  path: '/agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppSolicitacoesRoute = AppSolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppProfissionaisRoute = AppProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppMinhaAgendaRoute = AppMinhaAgendaRouteImport.update({
  id: '/minha-agenda',
  path: '/minha-agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppMeusPacientesRoute = AppMeusPacientesRouteImport.update({
  id: '/meus-pacientes',
  path: '/meus-pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppMeuPerfilRoute = AppMeuPerfilRouteImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const ApiSitemapDotxmlRoute = ApiSitemapDotxmlRouteImport.update({
  id: '/api/sitemap.xml',
  path: '/api/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/cliente': typeof ClienteRoute
  '/contato': typeof ContatoRoute
  '/especialidades': typeof EspecialidadesRoute
  '/profissionais': typeof ProfissionaisRoute
  '/sobre': typeof SobreRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/meu-perfil': typeof AppMeuPerfilRoute
  '/app/meus-pacientes': typeof AppMeusPacientesRoute
  '/app/minha-agenda': typeof AppMinhaAgendaRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/profissionais': typeof AppProfissionaisRoute
  '/app/solicitacoes': typeof AppSolicitacoesRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/auth': typeof AuthRoute
  '/cliente': typeof ClienteRoute
  '/contato': typeof ContatoRoute
  '/especialidades': typeof EspecialidadesRoute
  '/profissionais': typeof ProfissionaisRoute
  '/sobre': typeof SobreRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/meu-perfil': typeof AppMeuPerfilRoute
  '/app/meus-pacientes': typeof AppMeusPacientesRoute
  '/app/minha-agenda': typeof AppMinhaAgendaRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/profissionais': typeof AppProfissionaisRoute
  '/app/solicitacoes': typeof AppSolicitacoesRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/cliente': typeof ClienteRoute
  '/contato': typeof ContatoRoute
  '/especialidades': typeof EspecialidadesRoute
  '/profissionais': typeof ProfissionaisRoute
  '/sobre': typeof SobreRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/meu-perfil': typeof AppMeuPerfilRoute
  '/app/meus-pacientes': typeof AppMeusPacientesRoute
  '/app/minha-agenda': typeof AppMinhaAgendaRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/profissionais': typeof AppProfissionaisRoute
  '/app/solicitacoes': typeof AppSolicitacoesRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendamento'
    | '/app'
    | '/auth'
    | '/cliente'
    | '/contato'
    | '/especialidades'
    | '/profissionais'
    | '/sobre'
    | '/api/sitemap.xml'
    | '/app/agenda'
    | '/app/configuracoes'
    | '/app/financeiro'
    | '/app/meu-perfil'
    | '/app/meus-pacientes'
    | '/app/minha-agenda'
    | '/app/notificacoes'
    | '/app/pacientes'
    | '/app/profissionais'
    | '/app/solicitacoes'
    | '/app/usuarios'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendamento'
    | '/auth'
    | '/cliente'
    | '/contato'
    | '/especialidades'
    | '/profissionais'
    | '/sobre'
    | '/api/sitemap.xml'
    | '/app/agenda'
    | '/app/configuracoes'
    | '/app/financeiro'
    | '/app/meu-perfil'
    | '/app/meus-pacientes'
    | '/app/minha-agenda'
    | '/app/notificacoes'
    | '/app/pacientes'
    | '/app/profissionais'
    | '/app/solicitacoes'
    | '/app/usuarios'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/agendamento'
    | '/app'
    | '/auth'
    | '/cliente'
    | '/contato'
    | '/especialidades'
    | '/profissionais'
    | '/sobre'
    | '/api/sitemap.xml'
    | '/app/agenda'
    | '/app/configuracoes'
    | '/app/financeiro'
    | '/app/meu-perfil'
    | '/app/meus-pacientes'
    | '/app/minha-agenda'
    | '/app/notificacoes'
    | '/app/pacientes'
    | '/app/profissionais'
    | '/app/solicitacoes'
    | '/app/usuarios'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendamentoRoute: typeof AgendamentoRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClienteRoute: typeof ClienteRoute
  ContatoRoute: typeof ContatoRoute
  EspecialidadesRoute: typeof EspecialidadesRoute
  ProfissionaisRoute: typeof ProfissionaisRoute
  SobreRoute: typeof SobreRoute
  ApiSitemapDotxmlRoute: typeof ApiSitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais': {
      id: '/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof ProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especialidades': {
      id: '/especialidades'
      path: '/especialidades'
      fullPath: '/especialidades'
      preLoaderRoute: typeof EspecialidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamento': {
      id: '/agendamento'
      path: '/agendamento'
      fullPath: '/agendamento'
      preLoaderRoute: typeof AgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usuarios': {
      id: '/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/solicitacoes': {
      id: '/app/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/app/solicitacoes'
      preLoaderRoute: typeof AppSolicitacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profissionais': {
      id: '/app/profissionais'
      path: '/profissionais'
      fullPath: '/app/profissionais'
      preLoaderRoute: typeof AppProfissionaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pacientes': {
      id: '/app/pacientes'
      path: '/pacientes'
      fullPath: '/app/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notificacoes': {
      id: '/app/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/minha-agenda': {
      id: '/app/minha-agenda'
      path: '/minha-agenda'
      fullPath: '/app/minha-agenda'
      preLoaderRoute: typeof AppMinhaAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meus-pacientes': {
      id: '/app/meus-pacientes'
      path: '/meus-pacientes'
      fullPath: '/app/meus-pacientes'
      preLoaderRoute: typeof AppMeusPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meu-perfil': {
      id: '/app/meu-perfil'
      path: '/meu-perfil'
      fullPath: '/app/meu-perfil'
      preLoaderRoute: typeof AppMeuPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/sitemap.xml': {
      id: '/api/sitemap.xml'
      path: '/api/sitemap.xml'
      fullPath: '/api/sitemap.xml'
      preLoaderRoute: typeof ApiSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppMeuPerfilRoute: typeof AppMeuPerfilRoute
  AppMeusPacientesRoute: typeof AppMeusPacientesRoute
  AppMinhaAgendaRoute: typeof AppMinhaAgendaRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPacientesRoute: typeof AppPacientesRoute
  AppProfissionaisRoute: typeof AppProfissionaisRoute
  AppSolicitacoesRoute: typeof AppSolicitacoesRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppMeuPerfilRoute: AppMeuPerfilRoute,
  AppMeusPacientesRoute: AppMeusPacientesRoute,
  AppMinhaAgendaRoute: AppMinhaAgendaRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPacientesRoute: AppPacientesRoute,
  AppProfissionaisRoute: AppProfissionaisRoute,
  AppSolicitacoesRoute: AppSolicitacoesRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendamentoRoute: AgendamentoRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ClienteRoute: ClienteRoute,
  ContatoRoute: ContatoRoute,
  EspecialidadesRoute: EspecialidadesRoute,
  ProfissionaisRoute: ProfissionaisRoute,
  SobreRoute: SobreRoute,
  ApiSitemapDotxmlRoute: ApiSitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
