/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as EspecialidadesRouteImport } from './routes/especialidades'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AgendamentoRouteImport } from './routes/agendamento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClienteIndexRouteImport } from './routes/cliente.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ClienteLoginRouteImport } from './routes/cliente.login'
import { Route as AppWhatsappRouteImport } from './routes/app.whatsapp'
import { Route as AppUsuariosRouteImport } from './routes/app.usuarios'
import { Route as AppSolicitacoesRouteImport } from './routes/app.solicitacoes'
import { Route as AppProfissionaisRouteImport } from './routes/app.profissionais'
import { Route as AppPacientesRouteImport } from './routes/app.pacientes'
import { Route as AppNotificacoesRouteImport } from './routes/app.notificacoes'
import { Route as AppMinhaAgendaRouteImport } from './routes/app.minha-agenda'
import { Route as AppMeusPacientesRouteImport } from './routes/app.meus-pacientes'
import { Route as AppMeuPerfilRouteImport } from './routes/app.meu-perfil'
import { Route as AppMarketingRouteImport } from './routes/app.marketing'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppContaRouteImport } from './routes/app.conta'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp/webhook'
import { Route as ApiPublicTestWhatsappRouteImport } from './routes/api/public/test-whatsapp'
import { Route as ApiPublicHooksNotificacoesRouteImport } from './routes/api/public/hooks/notificacoes'
import { Route as ApiPublicHooksMetaRouteImport } from './routes/api/public/hooks/meta'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisRoute = ProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecialidadesRoute = EspecialidadesRouteImport.update({
  id: '/especialidades',
  path: '/especialidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentoRoute = AgendamentoRouteImport.update({
  id: '/agendamento',
  path: '/agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClienteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ClienteLoginRoute = ClienteLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ClienteRoute,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppSolicitacoesRoute = AppSolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppProfissionaisRoute = AppProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppMinhaAgendaRoute = AppMinhaAgendaRouteImport.update({
  id: '/minha-agenda',
  path: '/minha-agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppMeusPacientesRoute = AppMeusPacientesRouteImport.update({
  id: '/meus-pacientes',
  path: '/meus-pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppMeuPerfilRoute = AppMeuPerfilRouteImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppContaRoute = AppContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestWhatsappRoute = ApiPublicTestWhatsappRouteImport.update({
  id: '/api/public/test-whatsapp',
  path: '/api/public/test-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNotificacoesRoute =
  ApiPublicHooksNotificacoesRouteImport.update({
    id: '/api/public/hooks/notificacoes',
    path: '/api/public/hooks/notificacoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMetaRoute = ApiPublicHooksMetaRouteImport.update({
  id: '/api/public/hooks/meta',
  path: '/api/public/hooks/meta',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/contato': typeof ContatoRoute
  '/especialidades': typeof EspecialidadesRoute
  '/profissionais': typeof ProfissionaisRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/conta': typeof AppContaRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/meu-perfil': typeof AppMeuPerfilRoute
  '/app/meus-pacientes': typeof AppMeusPacientesRoute
  '/app/minha-agenda': typeof AppMinhaAgendaRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/profissionais': typeof AppProfissionaisRoute
  '/app/solicitacoes': typeof AppSolicitacoesRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/app/': typeof AppIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/api/public/test-whatsapp': typeof ApiPublicTestWhatsappRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/api/public/hooks/meta': typeof ApiPublicHooksMetaRoute
  '/api/public/hooks/notificacoes': typeof ApiPublicHooksNotificacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/especialidades': typeof EspecialidadesRoute
  '/profissionais': typeof ProfissionaisRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/conta': typeof AppContaRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/meu-perfil': typeof AppMeuPerfilRoute
  '/app/meus-pacientes': typeof AppMeusPacientesRoute
  '/app/minha-agenda': typeof AppMinhaAgendaRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/profissionais': typeof AppProfissionaisRoute
  '/app/solicitacoes': typeof AppSolicitacoesRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/app': typeof AppIndexRoute
  '/cliente': typeof ClienteIndexRoute
  '/api/public/test-whatsapp': typeof ApiPublicTestWhatsappRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/api/public/hooks/meta': typeof ApiPublicHooksMetaRoute
  '/api/public/hooks/notificacoes': typeof ApiPublicHooksNotificacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/contato': typeof ContatoRoute
  '/especialidades': typeof EspecialidadesRoute
  '/profissionais': typeof ProfissionaisRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/conta': typeof AppContaRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/meu-perfil': typeof AppMeuPerfilRoute
  '/app/meus-pacientes': typeof AppMeusPacientesRoute
  '/app/minha-agenda': typeof AppMinhaAgendaRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/profissionais': typeof AppProfissionaisRoute
  '/app/solicitacoes': typeof AppSolicitacoesRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/app/': typeof AppIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/api/public/test-whatsapp': typeof ApiPublicTestWhatsappRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/api/public/hooks/meta': typeof ApiPublicHooksMetaRoute
  '/api/public/hooks/notificacoes': typeof ApiPublicHooksNotificacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendamento'
    | '/app'
    | '/auth'
    | '/cliente'
    | '/contato'
    | '/especialidades'
    | '/profissionais'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/sobre'
    | '/app/agenda'
    | '/app/configuracoes'
    | '/app/conta'
    | '/app/financeiro'
    | '/app/marketing'
    | '/app/meu-perfil'
    | '/app/meus-pacientes'
    | '/app/minha-agenda'
    | '/app/notificacoes'
    | '/app/pacientes'
    | '/app/profissionais'
    | '/app/solicitacoes'
    | '/app/usuarios'
    | '/app/whatsapp'
    | '/cliente/login'
    | '/app/'
    | '/cliente/'
    | '/api/public/test-whatsapp'
    | '/api/whatsapp/webhook'
    | '/api/public/hooks/meta'
    | '/api/public/hooks/notificacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendamento'
    | '/auth'
    | '/contato'
    | '/especialidades'
    | '/profissionais'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/sobre'
    | '/app/agenda'
    | '/app/configuracoes'
    | '/app/conta'
    | '/app/financeiro'
    | '/app/marketing'
    | '/app/meu-perfil'
    | '/app/meus-pacientes'
    | '/app/minha-agenda'
    | '/app/notificacoes'
    | '/app/pacientes'
    | '/app/profissionais'
    | '/app/solicitacoes'
    | '/app/usuarios'
    | '/app/whatsapp'
    | '/cliente/login'
    | '/app'
    | '/cliente'
    | '/api/public/test-whatsapp'
    | '/api/whatsapp/webhook'
    | '/api/public/hooks/meta'
    | '/api/public/hooks/notificacoes'
  id:
    | '__root__'
    | '/'
    | '/agendamento'
    | '/app'
    | '/auth'
    | '/cliente'
    | '/contato'
    | '/especialidades'
    | '/profissionais'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/sobre'
    | '/app/agenda'
    | '/app/configuracoes'
    | '/app/conta'
    | '/app/financeiro'
    | '/app/marketing'
    | '/app/meu-perfil'
    | '/app/meus-pacientes'
    | '/app/minha-agenda'
    | '/app/notificacoes'
    | '/app/pacientes'
    | '/app/profissionais'
    | '/app/solicitacoes'
    | '/app/usuarios'
    | '/app/whatsapp'
    | '/cliente/login'
    | '/app/'
    | '/cliente/'
    | '/api/public/test-whatsapp'
    | '/api/whatsapp/webhook'
    | '/api/public/hooks/meta'
    | '/api/public/hooks/notificacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendamentoRoute: typeof AgendamentoRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClienteRoute: typeof ClienteRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  EspecialidadesRoute: typeof EspecialidadesRoute
  ProfissionaisRoute: typeof ProfissionaisRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  ApiPublicTestWhatsappRoute: typeof ApiPublicTestWhatsappRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
  ApiPublicHooksMetaRoute: typeof ApiPublicHooksMetaRoute
  ApiPublicHooksNotificacoesRoute: typeof ApiPublicHooksNotificacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais': {
      id: '/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof ProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especialidades': {
      id: '/especialidades'
      path: '/especialidades'
      fullPath: '/especialidades'
      preLoaderRoute: typeof EspecialidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamento': {
      id: '/agendamento'
      path: '/agendamento'
      fullPath: '/agendamento'
      preLoaderRoute: typeof AgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/cliente/login': {
      id: '/cliente/login'
      path: '/login'
      fullPath: '/cliente/login'
      preLoaderRoute: typeof ClienteLoginRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/app/whatsapp': {
      id: '/app/whatsapp'
      path: '/whatsapp'
      fullPath: '/app/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usuarios': {
      id: '/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/solicitacoes': {
      id: '/app/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/app/solicitacoes'
      preLoaderRoute: typeof AppSolicitacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profissionais': {
      id: '/app/profissionais'
      path: '/profissionais'
      fullPath: '/app/profissionais'
      preLoaderRoute: typeof AppProfissionaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pacientes': {
      id: '/app/pacientes'
      path: '/pacientes'
      fullPath: '/app/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notificacoes': {
      id: '/app/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/minha-agenda': {
      id: '/app/minha-agenda'
      path: '/minha-agenda'
      fullPath: '/app/minha-agenda'
      preLoaderRoute: typeof AppMinhaAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meus-pacientes': {
      id: '/app/meus-pacientes'
      path: '/meus-pacientes'
      fullPath: '/app/meus-pacientes'
      preLoaderRoute: typeof AppMeusPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meu-perfil': {
      id: '/app/meu-perfil'
      path: '/meu-perfil'
      fullPath: '/app/meu-perfil'
      preLoaderRoute: typeof AppMeuPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketing': {
      id: '/app/marketing'
      path: '/marketing'
      fullPath: '/app/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conta': {
      id: '/app/conta'
      path: '/conta'
      fullPath: '/app/conta'
      preLoaderRoute: typeof AppContaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-whatsapp': {
      id: '/api/public/test-whatsapp'
      path: '/api/public/test-whatsapp'
      fullPath: '/api/public/test-whatsapp'
      preLoaderRoute: typeof ApiPublicTestWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notificacoes': {
      id: '/api/public/hooks/notificacoes'
      path: '/api/public/hooks/notificacoes'
      fullPath: '/api/public/hooks/notificacoes'
      preLoaderRoute: typeof ApiPublicHooksNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/meta': {
      id: '/api/public/hooks/meta'
      path: '/api/public/hooks/meta'
      fullPath: '/api/public/hooks/meta'
      preLoaderRoute: typeof ApiPublicHooksMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContaRoute: typeof AppContaRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppMeuPerfilRoute: typeof AppMeuPerfilRoute
  AppMeusPacientesRoute: typeof AppMeusPacientesRoute
  AppMinhaAgendaRoute: typeof AppMinhaAgendaRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPacientesRoute: typeof AppPacientesRoute
  AppProfissionaisRoute: typeof AppProfissionaisRoute
  AppSolicitacoesRoute: typeof AppSolicitacoesRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContaRoute: AppContaRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppMeuPerfilRoute: AppMeuPerfilRoute,
  AppMeusPacientesRoute: AppMeusPacientesRoute,
  AppMinhaAgendaRoute: AppMinhaAgendaRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPacientesRoute: AppPacientesRoute,
  AppProfissionaisRoute: AppProfissionaisRoute,
  AppSolicitacoesRoute: AppSolicitacoesRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ClienteRouteChildren {
  ClienteLoginRoute: typeof ClienteLoginRoute
  ClienteIndexRoute: typeof ClienteIndexRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteLoginRoute: ClienteLoginRoute,
  ClienteIndexRoute: ClienteIndexRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendamentoRoute: AgendamentoRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ClienteRoute: ClienteRouteWithChildren,
  ContatoRoute: ContatoRoute,
  EspecialidadesRoute: EspecialidadesRoute,
  ProfissionaisRoute: ProfissionaisRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  ApiPublicTestWhatsappRoute: ApiPublicTestWhatsappRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
  ApiPublicHooksMetaRoute: ApiPublicHooksMetaRoute,
  ApiPublicHooksNotificacoesRoute: ApiPublicHooksNotificacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
